### ISSUE TITLE
Play 2.5.x support

### ISSUE THREAD

**Issue by etsrepo** [playframework/play-socket.io#1]
if I added dependency guice is not working

**Comment by gmethvin** [comment]
I doubt this will happen unless someone from the community wants to contribute a version for 2.5.x. If you're trying to get help I'd suggest the mailing list: https://groups.google.com/forum/#!forum/play-framework

**Comment by arminghm** [comment]
any update on this?
can we use play-socket.io with play 2.5.x?

**Comment by wsargent** [comment]
@arminghm 	No, this is not backported.

**Comment by marcospereira** [comment]
Play 2.5 is EOLed now. So this won't be backported to it.
