### ISSUE TITLE
How to handle disconnect event and private message

### ISSUE THREAD

**Issue by agemon** [playframework/play-socket.io#9]
Is there a way to handle disconnect event and private message?

In socket.io
```socket.on('disconnect', functionWhatever);```

```
// sending to individual socketid (private message)
socket.to(<socketid>).emit('hey', 'I just met you');
```
https://socket.io/docs/emit-cheatsheet/

Any help would be greatly appreciated.

**Comment by jroper** [comment]
Disconnection can be handled be handled by using an Akka streams `watchTermination` stage, eg:

```java
flow.watchTermination((m, termination) -> {
  termination.thenAccept(done -> {
    // Code here to handle termination
  });
  return m;
});
```

And not sure what you mean by "private message", socket.io is just a stream of messages, if you want to send a message, include it in the stream.

**Comment by agemon** [comment]
Thank you very much!
